services:
  - type: web
    name: mirror-trades-api
    env: python
    plan: free
    repo: https://github.com/ZoozFX/BuHamed
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
